baseURL = "https://naturallycooked.com"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Naturally Cooked - Restaurants Cooking With Wood"
[[menu.main]]
name = "Bakery"
parent = "Cuisine"
url = "https://naturallycooked.com/categories/bakery/"
weight = 3
[[menu.main]]
name = "Berlin"
parent = "Cities"
url = "https://naturallycooked.com/categories/berlin/"
weight = 1
[[menu.main]]
name = "Cities"
url = "#"
weight = 4
[[menu.main]]
name = "Turkish"
parent = "Cuisine"
url = "https://naturallycooked.com/categories/turkish/"
weight = 2
[[menu.main]]
name = "Pizza"
parent = "Cuisine"
url = "https://naturallycooked.com/categories/pizza/"
weight = 1
[[menu.main]]
name = "Cuisine"
url = "#"
weight = 3
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
page = ["HTML"]
[params]
author = "Naturally Cooked"
authorImage = "images/banner-img.png"
contactFormAction = "#"
copyright = "Naturally Cooked"
description = "Highlighting restaurants around the world that make the conscious choice to cook with wood"
googleAnalitycsID = "UA-155009140-1"
home = "Home"
homeLayoutToggle = false
logo = "images/logo.png"
[[params.footer.addresses]]
address = "European Union"
[[params.footer.addresses]]
address = "123 European Union Street"
[[params.footer.contacts]]
contactInfo = "Have you visited a restaurant that cooks with wood?"
[[params.footer.contacts]]
contactInfo = "Contact us via email - info@naturallycooked.com"
[params.instafeed]
accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = false
userID = "4044026246"
[params.main]
shortDescription = "A directory of restaurants that cook with wood"
subtitle = "cooked with heart"
title = "Eat food"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/headroom/headroom.js"
[[params.plugins.js]]
URL = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
URL = "plugins/masonry/masonry.js"
[[params.plugins.js]]
URL = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
URL = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
[params.search]
enable = true
[params.socialbuttons]
enabled = false
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
